
// Keyboard usage values, see usb.org's HID-usage-tables document, 
// chapter 10 Keyboard/Keypad page for more codes.

// Error Undefined
#define KEY_UNDEFINED_ERROR  0x03

// Modifiers
#define MOD_CONTROL_LEFT     0xE0
#define MOD_SHIFT_LEFT       0xE1
#define MOD_ALT_LEFT         0xE2
#define MOD_GUI_LEFT         0xE3
#define MOD_CONTROL_RIGHT    0xE4
#define MOD_SHIFT_RIGHT      0xE5
#define MOD_ALT_RIGHT        0xE6
#define MOD_GUI_RIGHT        0xE7

// Special Keys
#define KEY_APP              0x65
#define KEY_POWER            0x66
#define KEY_EXE              0x74
#define KEY_HELP             0x75
#define KEY_MENU             0x76
#define KEY_SELECT           0x77
#define KEY_STOP             0x78
#define KEY_AGAIN            0x79
#define KEY_UNDO             0x7A
#define KEY_CUT              0x7B
#define KEY_COPY             0x7C
#define KEY_PASTE            0x7D
#define KEY_FIND             0x7E

// Media Keys
#define KEY_MEDIA_MUTE       0x7F
#define KEY_MEDIA_VOLUME_INC 0x80
#define KEY_MEDIA_VOLUME_DEC 0x81
#define KEY_MEDIA_PLAY_PAUSE 0xCD
#define KEY_MEDIA_NEXT_TRACK 0xB5
#define KEY_MEDIA_PREV_TRACK 0xB6
#define KEY_MEDIA_STOP       0xB7

// Commons Keys
#define KEY_A                4
#define KEY_B                5
#define KEY_C                6
#define KEY_D                7
#define KEY_E                8
#define KEY_F                9
#define KEY_G                10
#define KEY_H                11
#define KEY_I                12
#define KEY_J                13
#define KEY_K                14
#define KEY_L                15
#define KEY_M                16
#define KEY_N                17
#define KEY_O                18
#define KEY_P                19
#define KEY_Q                20
#define KEY_R                21
#define KEY_S                22
#define KEY_T                23
#define KEY_U                24
#define KEY_V                25
#define KEY_W                26
#define KEY_X                27
#define KEY_Y                28
#define KEY_Z                29
#define KEY_1                30
#define KEY_2                31
#define KEY_3                32
#define KEY_4                33
#define KEY_5                34
#define KEY_6                35
#define KEY_7                36
#define KEY_8                37
#define KEY_9                38
#define KEY_0                39
#define KEY_ENTER            40
#define KEY_ESC              41
#define KEY_BACKSPACE        42
#define KEY_TAB              43
#define KEY_SPACE            44
#define KEY_MINUS            45
#define KEY_EQUAL            46
#define KEY_LEFT_BRACE       47
#define KEY_RIGHT_BRACE      48
#define KEY_BACKSLASH        49
#define KEY_NON_US_NUM       50
#define KEY_SEMICOLON        51
#define KEY_QUOTE            52
#define KEY_TILDE            53
#define KEY_COMMA            54
#define KEY_PERIOD           55
#define KEY_SLASH            56
#define KEY_CAPS_LOCK        57
#define KEY_F1               58
#define KEY_F2               59
#define KEY_F3               60
#define KEY_F4               61
#define KEY_F5               62
#define KEY_F6               63
#define KEY_F7               64
#define KEY_F8               65
#define KEY_F9               66
#define KEY_F10              67
#define KEY_F11              68
#define KEY_F12              69
#define KEY_PRINTSCREEN      70
#define KEY_SCROLL_LOCK      71
#define KEY_PAUSE            72
#define KEY_INSERT           73
#define KEY_HOME             74
#define KEY_PAGEUP           75
#define KEY_DELETE           76
#define KEY_END              77
#define KEY_PAGEDOWN         78
#define KEY_RIGHT            79
#define KEY_LEFT             80
#define KEY_DOWN             81
#define KEY_UP               82
#define KEY_NUM_LOCK         83
